# Generated by Django 4.2.16 on 2024-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_alter_tab_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='slug',
            field=models.SlugField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
