# Generated by Django 4.2.16 on 2024-12-12 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_tab_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf'),
        ),
    ]
