# Generated by Django 4.2.16 on 2024-12-12 12:02

import cloudinary.models
from django.db import migrations
import tab.models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0007_alter_tab_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[tab.models.validate_pdf_file], verbose_name='pdf'),
        ),
    ]
