# Generated by Django 4.2.16 on 2024-12-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
